### ISSUE TITLE
Couple small issues.

### ISSUE THREAD

**Issue by Healzangels** [ryakel/sonarr-yt-dlp#31]
Greetings!

Saw you had picked up [whatdaybob](https://github.com/whatdaybob/sonarr_youtubedl)'s project! I loved what it did minus a few issues I had run into so really glad to see it receive new updates.

Was wondering if you planned on maintaining this and would be open to a few bug fixes/issue reports. 

Thanks!

**Comment by ryakel** [comment]
Hey @Healzangels - I use it personally and will be doing my best to maintain it. Feel free to submit issues - also open to PRs!

**Comment by Healzangels** [comment]
That's awesome to hear! I'll close this out and open a proper issue for the two things I've noticed/had some issues with. Cheers! 
Thanks
