### ISSUE TITLE
Subtitle selection pulling all subtitles. 

### ISSUE THREAD

**Issue by Healzangels** [ryakel/sonarr-yt-dlp#33]
Greetings! 
Very cool again that you're supporting the project!

One issue I've been having is subtitle download. Following the configuration guide and specify only 1 subtitle end up seeing all possible subtitles grabbed.

Using this within the Playlist configuration:

`    subtitles: 
      languages: ['en']
      autogenerated: True
` 

Can provide any additional logs etc that may be needed. Thanks again!

**Comment by ryakel** [comment]
I have pushed a potential fix to the development branch. If you can `docker pull ryakel/sonarr-yt-dlp:dev` and let me know if it now respects the configuration setting.

**Comment by Healzangels** [comment]
Worked like a charm! Thanks

**Comment by ryakel** [comment]
reopening to link fix for future reference
