### ISSUE TITLE
Episode title customization

### ISSUE THREAD

**Issue by silentdragon14** [ryakel/sonarr-yt-dlp#48]
Needs an option for "Season 0" to be called "Specials".
Needs an option for leading zeros and accounting for seasons > 99 episodes for more leading zeros.
Show names don't always match Sonarr, "Hot Ones" vs "Hot Ones (2015)"

Possibly related, Sonarr is not refreshing and catching the new episodes.

**Comment by ryakel** [comment]
Thanks for the feedback. The first two are pretty edge cases. I will add them to the internal issue tracker and I will prioritize them if/when time permits. You are also welcome to submit a PR if you'd like them prioritized.

Can you provide me additional information on "Show names don't always match Sonarr"? Also, what version of Sonarr you are running?

**Comment by silentdragon14** [comment]
Sonarr version 4.0.3.1413 linuxserver/sonarr docker container.

Sonarr titles the "Hot Ones" tv show as "Hot Ones", but my naming settings use "Hot Ones (2015)"

In all the cases above, I think your software is making assumptions about default settings instead of following Sonarr settings.  Ideally, I'd rather you pull and follow how Sonarr is set or rely on Sonarr to import/rename the file itself after being triggered by your app.

**Comment by ryakel** [comment]
Yeah, I know that the original app made a lot of assumptions rather than pulling configurations directly from Sonarr. That said, I have had no issues with Sonarr properly renaming or placing files in the right directory. When time permits, I will see about standing up a server using non-standard configs for naming and see if I can replicate it.

**Comment by silentdragon14** [comment]
Update: After digging further, the "Hot Ones" vs "Hot Ones (2015)" discrepancy was due to my Media Management settings.  It would still be ideal if your software were to follow the settings found in the Media Management page.

**Comment by ryakel** [comment]
Thanks for the update. I will go ahead and close this issue out then.
