### ISSUE TITLE
Download format not being respected

### ISSUE THREAD

**Issue by silentdragon14** [ryakel/sonarr-yt-dlp#49]
i set "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" in the config but it's returning 720p.  I can run yt-dlp manually with the same format and get 1080p.

**Comment by ryakel** [comment]
By default,  the app does the following:  `bestvideo[width<=1920]+bestaudio/best[width<=1920]`. Can you give me an example of a video you are trying to pull so I can do some testing on my end? Thanks!

**Comment by silentdragon14** [comment]
with config set as:

> ytdl:
>     default_format: bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best

and

>   - title: Hot Ones
>     url: "https://www.youtube.com/FirstWeFeast"
>     format: bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best

https://www.youtube.com/watch?v=Kkx_FiSzbII kept coming back as 720p, despite 1080p being available.

**Comment by ryakel** [comment]
Try setting the format to `bestvideo[width<=1920]+bestaudio/best[width<=1920]` and see if you are still having the same trouble.

**Comment by silentdragon14** [comment]
> Try setting the format to `bestvideo[width<=1920]+bestaudio/best[width<=1920]` and see if you are still having the same trouble.

Using the above format it downloaded a WEBDL-2160p .webm
Confirmed my usual format still downloads a 720p

A new issue has cropped up, likely unrelated.  In both cases it is downloading the first YouTube Short of the channel, which is unrelated to the target video.

**Comment by ryakel** [comment]
Got it. I will explore the video quality issue and see if I can track down what is happening. 

I will also look into preventing shorts from getting downloaded. Having a short with a title that matches an episode seems like a fairly edge case,  but I agree that it shouldn’t be getting pulled either way.
